import type { StoryDef } from '../../common';

export const storyDef: StoryDef = {
  Blank: { options: { template: 'blank' } },
  JavaScript: { options: { template: 'javascript' }, storyName: 'JavaScript' },
  TypeScript: { options: { template: 'typescript' }, storyName: 'TypeScript' },
  React: { options: { template: 'react' } },
  ReactNative: { options: { template: 'react-native' } },
  Vue2: { options: { template: 'vue2' } },
  Vue3: { options: { template: 'vue' } },
  Angular: { options: { template: 'angular' } },
  Preact: { options: { template: 'preact' } },
  Svelte: { options: { template: 'svelte' } },
  Stencil: { options: { template: 'stencil' } },
  Solid: { options: { template: 'solid' } },
  MDX: { options: { template: 'mdx' } },
  Astro: { options: { template: 'astro' } },
  Riotjs: { options: { template: 'riot' } },
  Malinajs: { options: { template: 'malina' } },
  JQuery: { options: { template: 'jquery' }, storyName: 'jQuery' },
  Backbone: { options: { template: 'backbone' } },
  Knockout: { options: { template: 'knockout' } },
  Jest: { options: { template: 'jest' } },
  JestReact: { options: { template: 'jest-react' } },
  Bootstrap: { options: { template: 'bootstrap' } },
  TailwindCSS: { options: { template: 'tailwindcss' } },
  CoffeeScript: { options: { template: 'coffeescript' }, storyName: 'CoffeeScript' },
  LiveScript: { options: { template: 'livescript' }, storyName: 'LiveScript' },
  Civet: { options: { template: 'civet' } },
  Clio: { options: { template: 'clio' } },
  Imba: { options: { template: 'imba' } },
  ReScript: { options: { template: 'rescript' }, storyName: 'ReScript' },
  Reason: { options: { template: 'reason' } },
  Ocaml: { options: { template: 'ocaml' } },
  Python: { options: { template: 'python' } },
  PythonPyodide: { options: { template: 'python-wasm' } },
  R: { options: { template: 'r' } },
  Ruby: { options: { template: 'ruby' } },
  Go: { options: { template: 'go' } },
  PHP: { options: { template: 'php' } },
  Cpp: { options: { template: 'cpp' } },
  CppClang: { options: { template: 'cpp-wasm' } },
  Perl: { options: { template: 'perl' } },
  Lua: { options: { template: 'lua' } },
  Teal: { options: { template: 'teal' } },
  Fennel: { options: { template: 'fennel' } },
  Julia: { options: { template: 'julia' } },
  Scheme: { options: { template: 'scheme' } },
  CommonLisp: { options: { template: 'commonlisp' } },
  ClojureScript: { options: { template: 'clojurescript' }, storyName: 'ClojureScript' },
  Tcl: { options: { template: 'tcl' } },
  Markdown: { options: { template: 'markdown' } },
  AssemblyScript: { options: { template: 'assemblyscript' }, storyName: 'AssemblyScript' },
  WebAssemblyText: { options: { template: 'wat' }, storyName: 'WebAssembly Text' },
  SQL: { options: { template: 'sql' } },
  Prolog: { options: { template: 'prolog' } },
  Blockly: { options: { template: 'blockly' } },
  Diagram: { options: { template: 'diagrams' } },
};

export default storyDef;
